### ISSUE TITLE
Make sure results are reproducible

### ISSUE THREAD

**Issue by tomaszkosmala** [rangl-labs/netzerotc#63] opened 2021-11-15 10:28 UTC
- [ ] Create example with commands to reproduce the current issue (0.01% discrepancy in mean reward) from fresh clone
 
We observed that evaluation returns different result when we:
- evaluate multiple agents in a single python script, versus
- evaluate a single agent in one python script.

Progress so far:

1. A first bug has been fixed, which was reproduced by executing `local_agent_training_and_evaluation/testing_the_bug.py` on the branch `evaluation_error`
https://github.com/rangl-labs/netzerotc/blob/evaluation_error/local_agent_training_and_evaluation/testing_the_bug.py
2. A second similar bug has also been fixed, which occurred when resetting (but not deleting) the environment. 
3. We now want to create a check which verifies that the environment performs correctly

The current approach is described in [d0fc28e](https://github.com/rangl-labs/netzerotc/pull/65/commits/d0fc28e34b3e1feb7b37d906533fa2cfa79c5ee2), see comment below. An alternative approach which we considered was:

- [ ] Ensure that global object `param` is never modified -- full of constants 
- [ ] Create local structure `graph` to hold pycel object (which is initially set by `self.graph = None`)
- [ ] Ensure that `env.graph` is reset by `initialise_state`
- [ ] Test reproducibility

**Comment by jia-chenhua** [comment] 2021-11-16 13:43
My alternative approach:
- [ ] global object `param` is never created
- [ ] Parameters() not longer loads the .pkl compiled workbook
- [ ] Create attribute `pathways2Net0` of `state` to hold workbook object (which is initially set by explicitly loading the .pkl inside `initialise_state()` of `State:`)
- [ ]  `state.pathways2Net0` is reset by `initialise_state` or `env.reset()`
- [ ] `state.pathways2Net0` is updated by `randomise()` and `apply_action()`
- [ ] Test reproducibility

**Comment by moriartyjm** [comment] 2021-11-22 10:46
We have noticed further inconsistency: this time, between resetting and deleting the environment. So reopening issue.

**Comment by masonlr** [comment] 2021-11-22 11:12
Is the test to reproduce this here? 

https://github.com/rangl-labs/netzerotc/blob/9adff5566a66df6c46329601efa15a3c11732822/local_agent_training_and_evaluation/testing_the_bug.py#L63-L64

**Comment by jia-chenhua** [comment] 2021-11-22 11:16
Here is the latest fix: https://github.com/rangl-labs/netzerotc/commit/6a5f5749c30c02d7bf4698f96ed7584901ac0021

**Comment by masonlr** [comment] 2021-11-22 11:16
On the main branch, I can't reproduce the basic training because this no longer makes sense:

https://github.com/rangl-labs/netzerotc/blob/9adff5566a66df6c46329601efa15a3c11732822/local_agent_training_and_evaluation/train.py#L12-L14

There's no directory called `noise_sigma_sqrt0.00001_reward_plus_jobs_increment_40models1000episodes` checked into the codebase.

**Comment by jia-chenhua** [comment] 2021-11-22 11:20
> On the main branch, I can't reproduce the basic training because this no longer makes sense:
> 
> https://github.com/rangl-labs/netzerotc/blob/9adff5566a66df6c46329601efa15a3c11732822/local_agent_training_and_evaluation/train.py#L12-L14
> 
> There's no directory called `noise_sigma_sqrt0.00001_reward_plus_jobs_increment_40models1000episodes` checked into the codebase.

Should I push some trained models to GitHub?

**Comment by masonlr** [comment] 2021-11-22 11:29
> Should I push some trained models to GitHub?

The models are outputs, so don't need to be checked into the codebase: there needs to be a clear process so that a user can create these models. What a user would expect is that they can clone the repo and run the following:

```
cd local_agent_training_and_evaluation
python train.py
```

this would generate a model that can then be used with 

```
python testing_the_bug.py
```

**Comment by tomaszkosmala** [comment] 2021-11-22 11:39
For me `testing_the_bug.py` doesn't produce any error (the results are reproducible) so we need first understand what the problem is. I checked both with deleting&recreating the environment and with simply resetting it and the results were same.

**Comment by moriartyjm** [comment] 2021-11-22 21:22
> On the main branch, I can't reproduce the basic training because this no longer makes sense:
> 
> https://github.com/rangl-labs/netzerotc/blob/9adff5566a66df6c46329601efa15a3c11732822/local_agent_training_and_evaluation/train.py#L12-L14
> 
> There's no directory called `noise_sigma_sqrt0.00001_reward_plus_jobs_increment_40models1000episodes` checked into the codebase.

This has been addressed in #69 : the directory is now called `saved_models`

**Comment by moriartyjm** [comment] 2021-11-22 21:27
> For me `testing_the_bug.py` doesn't produce any error (the results are reproducible) so we need first understand what the problem is. I checked both with deleting&recreating the environment and with simply resetting it and the results were same.

I believe the bug has been fixed in #68 . Now, @jia-chenhua has implemented a simple test that `env.reset` works as expected: after calling `env.reset` it verifies that the two copies of the graph (ie the one we change, and the one we don’t change) are equal by summing the absolute differences between the corresponding pairs of nodes and checking that this gives the answer 0.

**Closed** 2021-11-22 21:30 UTC

**Comment by jia-chenhua** [comment] 2021-11-22 21:52
Although the reproducibility issue is fixed, the added lines https://github.com/rangl-labs/netzerotc/blob/6a5f5749c30c02d7bf4698f96ed7584901ac0021/environment/reference_environment_direct_deployment/env.py#L438-L439 and https://github.com/rangl-labs/netzerotc/blob/6a5f5749c30c02d7bf4698f96ed7584901ac0021/environment/reference_environment_direct_deployment/env.py#L452-L453 still bugs me, because no matter we reload the graph from .pkl or reset by https://github.com/rangl-labs/netzerotc/blob/6a5f5749c30c02d7bf4698f96ed7584901ac0021/environment/reference_environment_direct_deployment/env.py#L488, uncommenting/commenting out these 4 lines will result in 1e-4 relative difference in mean reward. In other words, when uncommenting these 4 lines, the results are same when reloading from .pkl or reset by `reset_param(param)`, and when commenting out these 4 lines, the results are also the same when reloading from .pkl or reset by `reset_param(param)`. But, there is a relative difference $`~O(10^{-4})`$ when commenting out these 4 lines or not.

Perhaps this is not really relevant to the `env.reset()` bug here, so I'll only be possible to fix it once I have more time.

**Comment by masonlr** [comment] 2021-11-25 02:05
Where is `env.check_reset()` called from? I was expecting this to be called from https://github.com/rangl-labs/netzerotc/blob/main/local_agent_training_and_evaluation/testing_the_bug.py but I can find it.

**Comment by masonlr** [comment] 2021-11-25 02:13
We need to formalise (in code) how the tests are intended to be run.

At the moment I don't know how to run the tests. For example, `testing_the_bug.py` is anticipating a local `MODEL_39.zip` file. There are two issues here:

1. `train.py` writes to `./saved_models/MODEL_39.zip`, but `testing_the_bug.py` is expecting `MODEL_39.zip` to be in the current folder.
2. To test the project, it's not feasible for a user to wait until 40 models have been trained in order to run the tests on model 39. The preparation time is too long here (>1 hour).

A user should be able to run the following:

```
cd local_agent_training_and_evaluation
pip install -r requirements.txt
python train.py
python testing_the_bug.py
```

and get confirmation that the tests have passed, i.e. none of the assert statements have failed.

**Comment by masonlr** [comment] 2021-11-25 02:15
I would suggest either (i) checking a `MODEL_test.zip` file into the source, or (ii) modifying the tests so that they create and test only `./saved_models/MODEL_0.zip`.

**Comment by masonlr** [comment] 2021-11-25 02:20
I will review the current issue on a merge request here https://github.com/rangl-labs/netzerotc/tree/review-63

**Comment by masonlr** [comment] 2021-11-25 02:55
> Where is `env.check_reset()` called from? I was expecting this to be called from https://github.com/rangl-labs/netzerotc/blob/main/local_agent_training_and_evaluation/testing_the_bug.py but I can't find it.

Have addressed this in https://github.com/rangl-labs/netzerotc/pull/71

**Comment by masonlr** [comment] 2021-11-25 02:55
> I suggest either (i) checking a `MODEL_test.zip` file into the source, or (ii) modifying the tests so that they create and test only `./saved_models/MODEL_0.zip`.

Have addressed this in https://github.com/rangl-labs/netzerotc/pull/71
